# shellcheck shell=bash

INSTALLER_URL=""

write_seed() {
	log_step "Pre-fill web installer"

	local install_dir="$FORUM_ROOT/install"
	local seed="$install_dir/install.seed.php"
	local index="$install_dir/index.php"

	local base_url="${SCHEME:-https}://${CFG_DOMAIN}/"
	INSTALLER_URL="${base_url}install/"

	if [ "${DRY_RUN:-0}" = "1" ]; then
		log_info "(dry-run) would write $seed (DB creds, baseURL=$base_url, admin email, blank password)"
		log_info "(dry-run) would inject ESO_SEED block into $index"
		return 0
	fi

	[ -f "$index" ] || die "Installer not found at $index"

	# --- generate the seed file via PHP for safe escaping ----------------
	ESO_FORUM_TITLE="${CFG_FORUM_TITLE:-My esoBB Forum}" \
	ESO_FORUM_DESC="${CFG_FORUM_DESCRIPTION:-A forum powered by esoBB.}" \
	ESO_DB_HOST="$DB_HOST" ESO_DB_USER="$DB_USER" \
	ESO_DB_PASS="$DB_PASS" ESO_DB_NAME="$DB_NAME" \
	ESO_ADMIN_USER="${CFG_ADMIN_USER:-admin}" \
	ESO_ADMIN_EMAIL="${CFG_ADMIN_EMAIL}" \
	ESO_BASE_URL="$base_url" \
	php -r '
		$seed = array(
			"forumTitle"        => getenv("ESO_FORUM_TITLE"),
			"forumDescription"  => getenv("ESO_FORUM_DESC"),
			"language"          => "English (casual)",
			"mysqlHost"         => getenv("ESO_DB_HOST"),
			"mysqlUser"         => getenv("ESO_DB_USER"),
			"mysqlPass"         => getenv("ESO_DB_PASS"),
			"mysqlDB"           => getenv("ESO_DB_NAME"),
			"sendEmail"         => "",
			"smtpAuth"          => "0",
			"smtpHost"          => "",
			"smtpPort"          => "",
			"smtpUser"          => "",
			"smtpPass"          => "",
			"showSmtpConfig"    => "",
			"adminUser"         => getenv("ESO_ADMIN_USER"),
			"adminEmail"        => getenv("ESO_ADMIN_EMAIL"),
			"adminPass"         => "",
			"adminConfirm"      => "",
			"tablePrefix"       => "et_",
			"characterEncoding" => "utf8mb4",
			"storageEngine"     => "InnoDB",
			"hashingMethod"     => "bcrypt",
			"baseURL"           => getenv("ESO_BASE_URL"),
			"friendlyURLs"      => "1",
		);
		echo "<?php\n// Generated by esoBB Bootstrap. Self-deletes after install. Do not commit.\nreturn " . var_export($seed, true) . ";\n";
	' >"$seed" || die "Failed to generate $seed"

	run "Securing seed file (owner ${WEB_USER}, mode 600)" \
		chown "${WEB_USER}:${WEB_USER}" "$seed"
	run "Restricting seed permissions" chmod 600 "$seed"
	php -l "$seed" >/dev/null || die "Generated seed file failed php -l"
	log_ok "Wrote installer seed: $seed"

	# --- inject the loader block into index.php --------------------------
	if grep -q 'ESO_SEED_BEGIN' "$index"; then
		log_ok "index.php already patched (ESO_SEED markers present); skipping."
	else
		local anchor='$_COOKIE = sanitize($_COOKIE);'
		grep -qF "$anchor" "$index" \
			|| die "Could not find injection anchor in $index (installer layout changed?)."

		local block
		block="$(cat "$TEMPLATES_DIR/index.php.seed-block.tmpl")"

		# Insert the block on the line after the anchor, preserving the file.
		ESO_BLOCK="$block" ESO_ANCHOR="$anchor" \
		php -r '
			$file   = $argv[1];
			$anchor = getenv("ESO_ANCHOR");
			$block  = getenv("ESO_BLOCK");
			$src    = file_get_contents($file);
			$pos    = strpos($src, $anchor);
			if ($pos === false) { fwrite(STDERR, "anchor not found\n"); exit(1); }
			$eol = strpos($src, "\n", $pos);
			if ($eol === false) $eol = strlen($src);
			$out = substr($src, 0, $eol + 1) . "\n" . $block . "\n" . substr($src, $eol + 1);
			file_put_contents($file, $out);
		' "$index" || die "Failed to inject seed block into $index"

		php -l "$index" >/dev/null || die "Patched index.php failed php -l"
		run "Restoring installer file ownership" \
			chown "${WEB_USER}:${WEB_USER}" "$index"
		log_ok "Injected ESO_SEED block into $index"
	fi

	log_ok "Installer pre-filled. Open: $INSTALLER_URL"
}
